import { type LanguagePreference } from "./preferences";

export function getCopy(language: LanguagePreference) {
  if (language === "EN") {
    return {
      navPocket: "My Pocket",
      navLobby: "Lobby",
      navDebt: "Ur Zeel",
      navSettings: "Settings",
      logout: "Logout",
      loggingOut: "Logging out...",
      appearance: "Appearance",
      light: "Light",
      dark: "Dark",
      totalBalance: "Total balance",
      loadingAccounts: "Loading accounts...",
      noAccounts: "No accounts found.",
      createAccount: "Create account",
      close: "Close",
      new: "New",
      accountName: "Account name",
      add: "Add",
      creating: "Creating...",
      showLess: "Show Less",
      showMore: "Show More",
      income: "Income",
      expense: "Expense",
      transfer: "Transfer",
      account: "Account",
      toAccount: "To Account",
      selectAccount: "Select account",
      selectDestination: "Select destination",
      category: "Category",
      internalMovement: "Internal movement",
      price: "Amount",
      description: "Description",
      date: "Date",
      addTransaction: "Add Transaction",
      saving: "Saving...",
      monthSummaryLoading: "Loading monthly summary...",
      lastTransactions: "Last transactions",
      all: "All",
      loadingTransactions: "Loading transactions...",
      noTransactions: "No transactions in this filter.",
      settings: "Settings",
      profileDefaults: "Profile & defaults",
      user: "User",
      displayName: "Display name",
      email: "Email",
      login: "Login",
      reset: "Reset",
      save: "Save",
      saved: "Saved",
      loading: "Loading...",
      preferences: "Preferences",
      language: "Language",
      mongolian: "Mongolian",
      english: "English",
      currency: "Currency",
      monthStart: "Month start",
      density: "Density",
      balanced: "Balanced",
      compact: "Compact",
      landing: "Landing",
      hideBalances: "Hide balances",
      enabled: "Enabled",
      disabled: "Disabled",
      monthChip: "Month",
      sharedFunds: "Shared funds",
      lobbyWorkspace: "Lobby workspace",
      sharedMoneyTitle: "Shared money, one dashboard per group.",
      sharedMoneyDescription:
        "Each lobby keeps one shared balance, one member roster, and one transaction history. Open a fund, review this month, and manage contributions and spending from the same dashboard shell as My Pocket.",
      lobbies: "Lobbies",
      members: "Members",
      balance: "Balance",
      noLobbies: "No lobbies yet",
      createFirstFund: "Create your first shared fund.",
      createFirstFundDescription:
        "Start with one lobby for rent, groceries, travel, or any monthly shared budget. The creator is added as owner automatically.",
      sharedLobby: "Shared lobby",
      noDescriptionYet: "No description yet.",
      updated: "Updated",
      openDashboard: "Open dashboard",
      reviewFund: "Review fund",
      createLobby: "Create lobby",
      openSharedFund: "Open a new shared fund.",
      createLobbyDescription:
        "This uses the real lobbies API. The authenticated user becomes the owner automatically and can add members from inside the lobby dashboard.",
      bestFor: "Best for",
      bestForExamples: "Rent, food, trips",
      membersHint: "Owner + shared roster",
      lobbyName: "Lobby name",
      lobbyDescription: "Description",
      createLobbyAction: "Create lobby",
      backToLobbyList: "Back to lobby list",
      sharedMonthlyFund: "Shared monthly fund",
      noDescription: "No description",
      role: "Role",
      sharedBalance: "Shared balance",
      currentBalance: "Current balance",
      overview: "Overview",
      transactions: "Transactions",
      reportingMonth: "Reporting month",
      selectMonth: "Select month",
      recentTransactions: "Recent transactions",
      noTransactionsMonth: "No transactions in this month.",
      topContributors: "Top contributors",
      net: "Net",
      count: "Count",
      lobbySettings: "Lobby settings",
      lobbySettingsDescription: "Rename or update the lobby description.",
      edit: "Edit",
      saveLobby: "Save lobby",
      incomeCategories: "Income categories",
      expenseCategories: "Expense categories",
      noIncomeCategories: "No income categories yet.",
      noExpenseCategories: "No expense categories yet.",
      lobbyTransactions: "Lobby transactions",
      delete: "Delete",
      lobbyMembers: "Lobby members",
      remove: "Remove",
      noMembersFound: "No members found.",
      addMember: "Add member",
      editTransaction: "Edit transaction",
      addTransactionLobby: "Add transaction",
      manageParticipants: "Manage who participates in the shared monthly fund.",
      updateSelectedTransaction: "Update the selected shared-fund transaction.",
      recordNewTransaction:
        "Record a new income or expense against the lobby balance.",
      transferFromPocket: "Transfer from My Pocket",
      transferFromPocketDescription:
        "Move money from one of your personal accounts into this lobby in one atomic transfer.",
      sourceAccount: "Source account",
      transferTargetMember: "Lobby member",
      personalAccountRequired:
        "Choose one of your personal accounts and transfer into your own lobby membership.",
      loadingPocketAccounts: "Loading personal accounts...",
      noPocketAccounts:
        "You need at least one personal account with balance before transferring into a lobby.",
      transferCompleted: "Transfer completed.",
      memberEmail: "Member email",
      userMustExist: "The user must already have an account in the app.",
      adding: "Adding...",
      onlyOwnersManageMembers: "Only lobby owners can add or remove members.",
      member: "Member",
      recordingAs: "Recording as",
      type: "Type",
      transactionDate: "Transaction date",
      change: "Change",
      saveTransaction: "Save transaction",
      cancelEdit: "Cancel edit",
      memberTransactionHelp:
        "Members can create transactions for themselves. Owners can edit or delete transactions for the whole lobby.",
      loginEyebrow: "Sign in",
      loginTitle: "Login",
      welcomeBackTitle: "Welcome back",
      welcomeBackDescription:
        "Track income, control spending, and keep your monthly finance clear in one place.",
      authReturnHint:
        "After authentication you will be returned to your dashboard.",
      continueWithAuth0: "Continue with Auth0",
      needPasswordHelp: "Need password help?",
      forgotPassword: "Forgot password",
      auth0NotConfigured:
        "Auth0 is not configured. Set AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET, AUTH0_SECRET, and APP_BASE_URL to enable login.",
      newHere: "New here?",
      createAccountLink: "Create account",
      signupEyebrow: "Get started",
      signupTitle: "Sign up",
      signupHeroTitle: "Build better money habits",
      signupHeroDescription:
        "Create your account and start tracking all your income and expense flows from today.",
      signupHeroHint:
        "You can add accounts, monthly summaries and transaction categories.",
      continueToAuth0Signup: "Continue to Auth0 sign up",
      alreadyHaveAccount: "Already have an account?",
      auth0SignupNotConfigured:
        "Auth0 is not configured. Configure Auth0 first, then use hosted sign up from this page.",
      recoveryEyebrow: "Recovery",
      recoveryTitle: "Forgot password",
      passwordRecovery: "Password recovery",
      resetThroughAuth0: "Reset password through Auth0",
      resetPassword: "Reset your password",
      auth0RecoveryDescription:
        "Auth0 Universal Login already includes password recovery, so the reset flow stays outside your app code.",
      auth0RecoveryDisabled:
        "Configure Auth0 to use hosted password reset through Universal Login.",
      auth0RecoveryHint:
        "Open the hosted login screen and use the built-in Forgot password action there.",
      auth0RecoverySigninHint:
        "After reset, sign in again to continue your dashboard.",
      continueToAuth0: "Continue to Auth0",
      resetFlowDescription:
        "Continue to Auth0 login, then click the built-in password reset link.",
      auth0ResetNotConfigured:
        "Password reset is handled only by Auth0 Universal Login. Add the Auth0 environment variables, then use the hosted login screen.",
      backTo: "Back to",
    };
  }

  return {
    navPocket: "Миний хэтэвч",
    navLobby: "Лобби",
    navDebt: "Өр Зээл",
    navSettings: "Тохиргоо",
    logout: "Гарах",
    loggingOut: "Гарч байна...",
    appearance: "Харагдац",
    light: "Цайвар",
    dark: "Харанхуй",
    totalBalance: "Нийт үлдэгдэл",
    loadingAccounts: "Данс ачаалж байна...",
    noAccounts: "Данс олдсонгүй.",
    createAccount: "Данс нэмэх",
    close: "Хаах",
    new: "Шинэ",
    accountName: "Дансны нэр",
    add: "Нэмэх",
    creating: "Үүсгэж байна...",
    showLess: "Хураах",
    showMore: "Дэлгэрүүлэх",
    income: "Орлого",
    expense: "Зарлага",
    transfer: "Шилжүүлэг",
    account: "Данс",
    toAccount: "Очих данс",
    selectAccount: "Данс сонгох",
    selectDestination: "Очих данс сонгох",
    category: "Ангилал",
    internalMovement: "Дотоод шилжүүлэг",
    price: "Дүн",
    description: "Тайлбар",
    date: "Огноо",
    addTransaction: "Гүйлгээ нэмэх",
    saving: "Хадгалж байна...",
    monthSummaryLoading: "Сарын мэдээлэл ачаалж байна...",
    lastTransactions: "Сүүлийн гүйлгээнүүд",
    all: "Бүгд",
    loadingTransactions: "Гүйлгээнүүд ачаалж байна...",
    noTransactions: "Энэ шүүлтэд гүйлгээ алга.",
    settings: "Тохиргоо",
    profileDefaults: "Профайл ба үндсэн тохиргоо",
    user: "Хэрэглэгч",
    displayName: "Харагдах нэр",
    email: "Имэйл",
    login: "Нэвтрэлт",
    reset: "Сэргээх",
    save: "Хадгалах",
    saved: "Хадгалагдсан",
    loading: "Ачаалж байна...",
    preferences: "Сонголтууд",
    language: "Хэл",
    mongolian: "Монгол",
    english: "Англи",
    currency: "Валют",
    monthStart: "Сарын эхлэх өдөр",
    density: "Нягтрал",
    balanced: "Энгийн",
    compact: "Шахуу",
    landing: "Эхлэх хуудас",
    hideBalances: "Дүн нууцлах",
    enabled: "Идэвхтэй",
    disabled: "Идэвхгүй",
    monthChip: "Сар",
    sharedFunds: "Хамтын сан",
    lobbyWorkspace: "Лобби орчин",
    sharedMoneyTitle: "Нэг баг, нэг shared сангийн самбар.",
    sharedMoneyDescription:
      "Лобби бүр нэг shared balance, нэг гишүүдийн бүртгэл, нэг гүйлгээний түүхтэй. Сан нээгээд, энэ сарыг хянаж, орлого зарлагыг нэг dashboard-оос удирдана.",
    lobbies: "Лоббинууд",
    members: "Гишүүд",
    balance: "Үлдэгдэл",
    noLobbies: "Лобби алга",
    createFirstFund: "Анхны shared сангаа нээ.",
    createFirstFundDescription:
      "Түрээс, хоол, аялал эсвэл ямар ч shared budget-аар нэг лобби эхлүүл. Үүсгэгч owner болж автоматаар нэмэгдэнэ.",
    sharedLobby: "Shared лобби",
    noDescriptionYet: "Тайлбар алга.",
    updated: "Шинэчлэгдсэн",
    openDashboard: "Самбар нээх",
    reviewFund: "Сан харах",
    createLobby: "Лобби үүсгэх",
    openSharedFund: "Шинэ shared сан нээ.",
    createLobbyDescription:
      "Энэ нь бодит lobbies API ашиглаж байна. Нэвтэрсэн хэрэглэгч owner болж автоматаар нэмэгдэнэ, дараа нь дотроос нь member нэмнэ.",
    bestFor: "Тохиромжтой",
    bestForExamples: "Түрээс, хоол, аялал",
    membersHint: "Owner + shared бүртгэл",
    lobbyName: "Лоббиний нэр",
    lobbyDescription: "Тайлбар",
    createLobbyAction: "Лобби үүсгэх",
    backToLobbyList: "Лоббиний жагсаалт руу",
    sharedMonthlyFund: "Сарын хамтын сан",
    noDescription: "Тайлбар алга",
    role: "Эрх",
    sharedBalance: "Хамтын үлдэгдэл",
    currentBalance: "Одоогийн үлдэгдэл",
    overview: "Тойм",
    transactions: "Гүйлгээ",
    reportingMonth: "Тайлант сар",
    selectMonth: "Сар сонгох",
    recentTransactions: "Сүүлийн гүйлгээнүүд",
    noTransactionsMonth: "Энэ сард гүйлгээ алга.",
    topContributors: "Идэвхтэй оролцогчид",
    net: "Цэвэр дүн",
    count: "Тоо",
    lobbySettings: "Лоббиний тохиргоо",
    lobbySettingsDescription: "Нэр болон тайлбарыг шинэчилнэ.",
    edit: "Засах",
    saveLobby: "Лобби хадгалах",
    incomeCategories: "Орлогын ангиллууд",
    expenseCategories: "Зарлагын ангиллууд",
    noIncomeCategories: "Орлогын ангилал алга.",
    noExpenseCategories: "Зарлагын ангилал алга.",
    lobbyTransactions: "Лоббиний гүйлгээнүүд",
    delete: "Устгах",
    lobbyMembers: "Лоббиний гишүүд",
    remove: "Хасах",
    noMembersFound: "Гишүүн алга.",
    addMember: "Гишүүн нэмэх",
    editTransaction: "Гүйлгээ засах",
    addTransactionLobby: "Гүйлгээ нэмэх",
    manageParticipants: "Хамтын санд оролцогчдыг удирдана.",
    updateSelectedTransaction: "Сонгосон shared гүйлгээг шинэчилнэ.",
    recordNewTransaction:
      "Лоббиний үлдэгдэл дээр шинэ орлого эсвэл зарлага бүртгэнэ.",
    transferFromPocket: "Миний хэтэвчээс шилжүүлэх",
    transferFromPocketDescription:
      "Өөрийн хувийн данснаас энэ лобби руу мөнгийг нэг атомик шилжүүлгээр нэмнэ.",
    sourceAccount: "Эх данс",
    transferTargetMember: "Лоббиний гишүүн",
    personalAccountRequired:
      "Өөрийн хувийн дансаа сонгоод, зөвхөн өөрийн лобби гишүүнчлэл рүү шилжүүлнэ.",
    loadingPocketAccounts: "Хувийн дансууд ачаалж байна...",
    noPocketAccounts:
      "Лобби руу шилжүүлэхийн өмнө үлдэгдэлтэй дор хаяж нэг хувийн данс хэрэгтэй.",
    transferCompleted: "Шилжүүлэг амжилттай.",
    memberEmail: "Гишүүний имэйл",
    userMustExist: "Тэр хэрэглэгч app дотор бүртгэлтэй байх ёстой.",
    adding: "Нэмж байна...",
    onlyOwnersManageMembers: "Зөвхөн owner гишүүн нэмэх, хасах эрхтэй.",
    member: "Гишүүн",
    recordingAs: "Дараах гишүүнээр бүртгэж байна",
    type: "Төрөл",
    transactionDate: "Гүйлгээний огноо",
    change: "Солих",
    saveTransaction: "Гүйлгээ хадгалах",
    cancelEdit: "Засварыг цуцлах",
    memberTransactionHelp:
      "Гишүүд зөвхөн өөрийнхөө гүйлгээг бүртгэнэ. Owner бүх лоббиний гүйлгээг засах, устгах эрхтэй.",
    loginEyebrow: "Нэвтрэх",
    loginTitle: "Нэвтрэх",
    welcomeBackTitle: "Буцаад тавтай морил",
    welcomeBackDescription:
      "Орлогоо хянаж, зарлагаа удирдаж, сарын санхүүгээ нэг дор цэгцтэй байлга.",
    authReturnHint: "Нэвтэрсний дараа таны сонгосон самбар руу буцна.",
    continueWithAuth0: "Auth0-оор үргэлжлүүлэх",
    needPasswordHelp: "Нууц үгийн тусламж хэрэгтэй юу?",
    forgotPassword: "Нууц үг мартсан",
    auth0NotConfigured:
      "Auth0 тохируулагдаагүй байна. AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET, AUTH0_SECRET, APP_BASE_URL утгуудыг нэм.",
    newHere: "Шинээр орж байна уу?",
    createAccountLink: "Бүртгэл үүсгэх",
    signupEyebrow: "Эхлэх",
    signupTitle: "Бүртгүүлэх",
    signupHeroTitle: "Мөнгөө илүү зөв удирд",
    signupHeroDescription:
      "Өөрийн бүртгэлээ үүсгээд өнөөдрөөс эхлэн орлого, зарлагаа нэг дор хяна.",
    signupHeroHint:
      "Та данс, сарын summary, transaction category-уудаа удирдаж чадна.",
    continueToAuth0Signup: "Auth0 бүртгэл рүү үргэлжлүүлэх",
    alreadyHaveAccount: "Бүртгэлтэй юу?",
    auth0SignupNotConfigured:
      "Auth0 тохируулаад дараа нь энэ хуудсаас hosted sign up ашиглана.",
    recoveryEyebrow: "Сэргээх",
    recoveryTitle: "Нууц үг мартсан",
    passwordRecovery: "Нууц үг сэргээх",
    resetThroughAuth0: "Auth0-оор нууц үг сэргээх",
    resetPassword: "Нууц үгээ сэргээх",
    auth0RecoveryDescription:
      "Auth0 Universal Login дотор password recovery бэлэн байдаг тул reset flow нь аппын кодоос тусдаа явна.",
    auth0RecoveryDisabled:
      "Hosted password reset ашиглахын тулд Auth0-оо тохируул.",
    auth0RecoveryHint:
      "Hosted login дэлгэцийг нээгээд built-in Forgot password үйлдлийг ашигла.",
    auth0RecoverySigninHint:
      "Сэргээсний дараа дахин нэвтэрч самбар руугаа орно.",
    continueToAuth0: "Auth0 руу үргэлжлүүлэх",
    resetFlowDescription:
      "Auth0 login руу ороод built-in password reset холбоосыг дар.",
    auth0ResetNotConfigured:
      "Password reset-ийг зөвхөн Auth0 Universal Login удирдана. Auth0 env-үүдээ нэмээд hosted login дэлгэц ашигла.",
    backTo: "Буцах",
  };
}
